### ISSUE TITLE
Cannot kompile:  Could not find sorts: [MInt]

### ISSUE THREAD

**Issue by vasil-sd** [kframework/X86-64-semantics#10]
Trying to kompile: ../scripts/kompile.pl --backend java
but without success:

Importing: Source(/home/vasil/work/isa/X86-64-semantics-master/semantics/x86-c-library.k)
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Could not find sorts: [MInt]
        Source(/home/vasil/work/isa/X86-64-semantics-master/semantics/x86-memory.k)
        Location(80,21,82,50)
        at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:126)
        at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:80)
        at org.kframework.definition.Module.$anonfun$checkSorts$1(outer.scala:318)
        at org.kframework.definition.Module.$anonfun$checkSorts$1$adapted(outer.scala:311)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at org.kframework.definition.Module.checkSorts(outer.scala:311)
        at org.kframework.definition.FlatModule.toModule(outer-ext.scala:109)
        at org.kframework.kore.convertors.KILtoKORE.apply(KILtoKORE.java:109)
        at org.kframework.parser.concrete2kore.ParserUtils.lambda$loadModules$4(ParserUtils.java:223)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.kframework.parser.concrete2kore.ParserUtils.loadModules(ParserUtils.java:223)
        at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:275)
        at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:256)
        at org.kframework.kompile.DefinitionParsing.parseDefinition(DefinitionParsing.java:187)
        at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:156)
        at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:165)
        at org.kframework.kompile.Kompile.run(Kompile.java:133)
        at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
Command exited with non-zero status 113

What  I am doing wrong?

K-tools from latest release.

**Comment by sdasgup3** [comment]
Dear @vasil-sd,
Sorry for the confusion. 

Due to [polymorphic sort support](https://github.com/kframework/k/pull/839), the syntax of machine integers aka MInt have changed a bit and the current x86-64 semantics is not responsive to that.

Before I port my semantis to the new syntax, I would suggest you to either checkout `git checkout 45a4243af6e4cd42a4212e5c7575e876898ec38b`, which is a commit before the aforementioned change or use my [forked repository](https://github.com/sdasgup3/k.git) (which I currently use for the purpose). I hope this should get you moving for the time-being.

Let me know in case you get into other issues

**Comment by vasil-sd** [comment]
Thanks! I'll try to use your forked repo.

**Comment by sdasgup3** [comment]
@vasil-sd I am closing this for now. However, feel free to reopen in case you face other related  issues.
